### PR TITLE
More refined GeNN

### PR DESCRIPTION
**Pull request by neworderofjamie**
I'm now rather in finishing things off before I leave mode so, rather than continue messing with my DVS gesture model on my under-powered laptop, I reproduced a similar thing to your edge-detection model in GeNN and tidied up the API a little (a little hazy on you intentions re the logic in ``__init__.py`` so please let me know if you're happy with my addition. Also, GeNN now supports polarity when events are provided via ``TensorBuffer::set_vector`` - should be easy to extend to CUDA+CPU

### CODE REVIEW

**Comment by neworderofjamie** [comment]
I've made ``read_genn`` a method of all the ``InputXXX`` classes as we discussed although it did involve rather more copy-pasting that I would have hoped as nanobind threw a ``RuntimeError: nb_type_init(): invalid number of bases!`` when I tried implementing this functionality in a mixin - I may just be missing something.

**Review by Jegp — APPROVED** [review]
Thank you for following up on this @neworderofjamie! I'm grateful we can wrap this up in a slightly neater form.

I agree the mixin approach would be beneficial. For now, I think this is already much better, and we're only talking about ~20 LOC we'd have to maintain going forward.

One comment, though, is that we risk the GeNN API deprecating without a regression test. I'm uncertain if I'll be able to test every endpoint for every release myself, at least :-)

Could you give me a thumbs-up if you're OK with me squashing and merging this?

**Comment by neworderofjamie** [comment]
Agree a regression test will be nice - will try and add one (probably with GeNN mocked to save complexity in the test setup) when I get some time

**Comment by Jegp** [comment]
No pressure at all! I'm myself quite swamped, so I recognize regression tests aren't the highest of priorities :-)

What are your thoughts on merging this for now? I think it's already a solid improvement over status quo. And then when we/you/I find the time, we can always put in tests.

**Comment by neworderofjamie** [comment]
As we rather pre-emptively merged my previous, actively bad attempt I think it makes sense to at least improve the situation with this PR 😄

**Comment by Jegp** [comment]
Brilliant. Thanks again for your efforts. Let's keep talking to make this more stable going forward :-)

**Pull request merged**
